Feature/project init
Home-Stockpile/stockpile-fe pull request #3
Opened 2022-11-21 14:25 UTC by Avareco

Project inited, typescript tryed

2022-11-21 14:58 UTC, hollote requested changes

2022-11-21 14:58 UTC, hollote commented on env.d.ts
> +/// <reference types="vite/client" />
what does this line do?

2022-11-21 14:58 UTC, hollote commented on package.json
> +    "@rushstack/eslint-patch": "^1.1.4",
why this dependency is added?

2022-11-21 14:58 UTC, hollote commented on package.json
> +    "npm-run-all": "^4.1.5",
why this dependency is added?

2022-11-22 11:31 UTC, Avareco commented on env.d.ts
> +/// <reference types="vite/client" />
File deleted

2022-11-22 11:33 UTC, Avareco commented on src/App.vue
> +interface IData {
For testing, but we don't need in it

2022-11-22 11:33 UTC, Avareco commented on package.json
> +    "npm-run-all": "^4.1.5",
dependency deleted

2022-11-22 12:55 UTC, merged