feature/41 added table
Home-Stockpile/stockpile-fe pull request #42
Opened 2023-01-12 10:17 UTC by Avareco

2023-01-12 12:10 UTC, hollote requested changes
Please provide an image

2023-01-12 17:02 UTC, Avareco commented
![image](https://user-images.githubusercontent.com/31128616/212132002-43b60d05-e14b-435f-9d3a-b127ba9046a5.png)

2023-01-12 17:08 UTC, Avareco commented
Also I've changed expanding logic - now item expands only on triangle click

2023-01-17 14:26 UTC, hollote approved these changes

2023-01-17 14:56 UTC, merged